"""
Evaluate the classical CV/OCR pipeline against a labelled dataset.

Synthetic invoices rendered with real TrueType fonts and scan-like
degradation (blur + noise + skew) — ground truth is known EXACTLY (build
with scripts/make_invoice_dataset.py), so CER/WER/token-F1 are rigorous, not
a proxy. (The LLM extraction layer has its own comparison harness —
scripts/evaluate_llm.py — since it measures a different thing: structured
field accuracy per model, not raw text recognition.)

Usage:
    python scripts/evaluate.py                       # default labelled dir
    python scripts/evaluate.py --baseline            # add raw-Tesseract column
    python scripts/evaluate.py --report RESULTS.md   # also write a markdown report
"""

import argparse
import glob
import json
import os
import sys
import time

import cv2
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from src import evaluation as ev
from src.pipeline import DocumentOCRPipeline
from src.tesseract_setup import ensure_tesseract

LABELLED = os.path.join(ROOT, "data", "invoices", "synthetic")


# ---------------------------------------------------------------------------
def raw_tesseract(path):
    """Baseline: plain Tesseract on the raw grayscale image, --psm 6."""
    import pytesseract
    ensure_tesseract()
    gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    return pytesseract.image_to_string(gray, config="--oem 3 --psm 6")


def load_labelled(d):
    pairs = []
    for img_path in sorted(glob.glob(os.path.join(d, "*.png"))):
        stem = os.path.splitext(img_path)[0]
        gt_path = stem + ".gt.txt"
        if not os.path.isfile(gt_path):
            continue
        with open(gt_path, encoding="utf-8") as f:
            gt = f.read()
        struct = None
        if os.path.isfile(stem + ".json"):
            with open(stem + ".json", encoding="utf-8") as f:
                struct = json.load(f)
        pairs.append((img_path, gt, struct))
    return pairs


def eval_labelled(name, textfn, pairs, verbose=False):
    agg = {"cer": [], "wer": [], "token_recall": [],
           "token_precision": [], "token_f1": []}
    fields = {"invoice_no": 0, "total": 0, "date": 0}
    n_fields = 0
    t0 = time.time()

    for img_path, gt, struct in pairs:
        try:
            hyp = textfn(img_path)
        except Exception as e:
            hyp = ""
            if verbose:
                print(f"  [{os.path.basename(img_path)}] ERROR: {e}")
        m = ev.evaluate_pair(gt, hyp)
        for k in agg:
            agg[k].append(m[k])
        if struct:
            fa = ev.field_accuracy(struct, hyp)
            for k in fields:
                fields[k] += int(fa[k])
            n_fields += 1
        if verbose:
            print(f"  {os.path.basename(img_path):14s} "
                  f"CER={m['cer']*100:6.2f}%  WER={m['wer']*100:6.2f}%  "
                  f"F1={m['token_f1']*100:6.2f}%")

    s = {k: float(np.mean(v)) if v else 0.0 for k, v in agg.items()}
    s["fields"] = {k: (fields[k] / n_fields if n_fields else 0.0) for k in fields}
    s["sec_per_doc"] = (time.time() - t0) / max(1, len(pairs))
    s["n"] = len(pairs)
    s["name"] = name
    return s


def print_labelled(s):
    print(f"\n=== labelled: {s['name']}  ({s['n']} invoices) ===")
    print(f"  CER (char error) : {s['cer']*100:6.2f}%   ->  char accuracy {100-s['cer']*100:5.2f}%")
    print(f"  WER (word error) : {s['wer']*100:6.2f}%")
    print(f"  Token recall     : {s['token_recall']*100:6.2f}%")
    print(f"  Token precision  : {s['token_precision']*100:6.2f}%")
    print(f"  Token F1         : {s['token_f1']*100:6.2f}%")
    print(f"  Field accuracy   : inv_no={s['fields']['invoice_no']*100:.0f}%  "
          f"total={s['fields']['total']*100:.0f}%  date={s['fields']['date']*100:.0f}%")
    print(f"  Speed            : {s['sec_per_doc']:.2f} s/doc")


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------
def write_report(path, pipe_s, base_s, tess_ver):
    L = []
    L.append("# OCR Pipeline — Evaluation Results\n")
    L.append(f"_Tesseract {tess_ver} · generated by `scripts/evaluate.py`. "
             "Regenerate with `python scripts/evaluate.py --baseline "
             "--report RESULTS.md` — every number below is measured, not "
             "hand-written._\n")

    L.append("## Classical CV/OCR pipeline (labelled invoices, exact ground truth)\n")
    L.append("Synthetic invoices rendered with real TrueType fonts and "
             "scan-like degradation (blur + noise + skew). Ground truth is known "
             "exactly, so CER/WER are rigorous, not a proxy.\n")
    L.append("| Configuration | CER | Char acc. | WER | Token-F1 | inv_no | total | date | s/doc |")
    L.append("|---|--:|--:|--:|--:|--:|--:|--:|--:|")

    def row(s):
        f = s["fields"]
        return (f"| {s['name']} | {s['cer']*100:.2f}% | {100-s['cer']*100:.2f}% | "
                f"{s['wer']*100:.2f}% | {s['token_f1']*100:.2f}% | "
                f"{f['invoice_no']*100:.0f}% | {f['total']*100:.0f}% | "
                f"{f['date']*100:.0f}% | {s['sec_per_doc']:.2f} |")
    if base_s:
        L.append(row(base_s))
    L.append(row(pipe_s))
    L.append("")
    if base_s:
        gain = base_s["cer"] - pipe_s["cer"]
        L.append(f"> The full pipeline cuts the character error rate by "
                 f"**{gain*100:.2f} points** vs. raw Tesseract "
                 f"({base_s['cer']*100:.2f}% → {pipe_s['cer']*100:.2f}%).\n")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"\nReport written to {path}")
    return "\n".join(L)


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--labelled", default=LABELLED)
    ap.add_argument("--baseline", action="store_true",
                    help="also evaluate raw Tesseract on the labelled set")
    ap.add_argument("--report", default=None, help="write a markdown report here")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    tess_bin = ensure_tesseract()
    if not tess_bin:
        print("ERROR: Tesseract not found. Run scripts/install_tesseract_local.sh "
              "or `apt-get install tesseract-ocr`.")
        sys.exit(1)
    import pytesseract
    tess_ver = str(pytesseract.get_tesseract_version())
    print(f"Tesseract: {tess_ver}")

    pl = DocumentOCRPipeline()

    pairs = load_labelled(args.labelled)
    if not pairs:
        print(f"\nNo labelled data in {args.labelled} — generate it with:\n"
              "  python scripts/make_invoice_dataset.py --n 12 --degrade scan")
        sys.exit(1)

    print(f"\nLabelled set: {len(pairs)} invoices in {args.labelled}")
    base_s = None
    if args.baseline:
        base_s = eval_labelled("Raw Tesseract (`--psm 6`)", raw_tesseract,
                               pairs, verbose=args.verbose)
        print_labelled(base_s)
    pipe_s = eval_labelled("**This pipeline**", pl.image_to_text, pairs,
                           verbose=args.verbose)
    print_labelled(pipe_s)

    if args.report:
        write_report(args.report, pipe_s, base_s, tess_ver)


if __name__ == "__main__":
    main()
