[theme]
base = "light"
primaryColor = "#2B4B7E"
backgroundColor = "#FBFBF9"
secondaryBackgroundColor = "#F2F1EC"
textColor = "#1A1B1D"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
